# Generated by Django 5.0.6 on 2024-06-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='categoyr',
            new_name='category',
        ),
    ]
